apiVersion: v1
kind: Pod
metadata:
  name: admin-pod
  namespace: admin
spec:
  serviceAccountName: admin-sa
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "infinity"]
