apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # base64 encoded values
  mysql-root-password: cGFzc3dvcmQ=        
  mysql-user: d3B1c2Vy                   
  mysql-password: cGFzc3dvcmQ=           